# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.0595, 0.6863, 0.7973, 0.3339, 0.1886, 0.1837, 0.7048],
        [0.8009, 0.5194, 0.7930, 0.8836, 0.5699, 0.7082, 0.3504],
        [0.1127, 0.3182, 0.3270, 0.3142, 0.9684, 0.7305, 0.8753],
        [0.9702, 0.7764, 0.2040, 0.9196, 0.8249, 0.1224, 0.6913],
        [0.9878, 0.5115, 0.5622, 0.9779, 0.5018, 0.8870, 0.6494],
        [0.0433, 0.2000, 0.7174, 0.9250, 0.4773, 0.9105, 0.0848],
        [0.6339, 0.6815, 0.6337, 0.0924, 0.8060, 0.8662, 0.3623]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
y = torch.rand(1, 7)
# Perform matrix multiplication
x @ y.T

tensor([[1.6389],
        [2.4644],
        [1.6918],
        [2.8848],
        [2.7419],
        [1.5001],
        [1.8508]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7, 7)
y = torch.rand(1, 7)


# Matrix multiply tensors
x @ y.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")
# Create two random tensors on GPU
x = torch.rand(size=(2, 3)).to(device)
y = torch.rand(size=(2, 3)).to(device)
print(x, y)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(x, y.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [28]:
# Find max
print(f"max_value is {torch.max(result)}")
# Find min
print(f"min_value is {torch.min(result)}")

max_value is 0.5617256760597229
min_value is 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
print(f"max value index is {torch.argmax(result)}")

# Find arg min
print(f"min value index is {torch.argmin(result)}")

max value index is 3
min value index is 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [40]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand(1, 1, 1, 10)

# Remove single dimensions
x_squeezed = x.squeeze()

# Print out tensors and their shapes
print(x, x.shape)
print(x_squeezed, x_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
